"""initial schema

Revision ID: 8067fc18fa97
Revises: 
Create Date: 2026-08-18 00:19:51.284863

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8067fc18fa97'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certifications',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('issuer_logo_url', sa.String(length=512), nullable=True),
    sa.Column('issued_at', sa.Date(), nullable=True),
    sa.Column('expires_at', sa.Date(), nullable=True),
    sa.Column('credential_id', sa.String(length=255), nullable=True),
    sa.Column('credential_url', sa.String(length=1024), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_certifications'))
    )
    op.create_index(op.f('ix_certifications_is_visible'), 'certifications', ['is_visible'], unique=False)
    op.create_index(op.f('ix_certifications_issued_at'), 'certifications', ['issued_at'], unique=False)
    op.create_index(op.f('ix_certifications_position'), 'certifications', ['position'], unique=False)
    op.create_table('contact_messages',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_spam', sa.Boolean(), nullable=False),
    sa.Column('replied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('referrer', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contact_messages'))
    )
    op.create_index(op.f('ix_contact_messages_email'), 'contact_messages', ['email'], unique=False)
    op.create_index(op.f('ix_contact_messages_is_archived'), 'contact_messages', ['is_archived'], unique=False)
    op.create_index(op.f('ix_contact_messages_is_read'), 'contact_messages', ['is_read'], unique=False)
    op.create_index(op.f('ix_contact_messages_is_spam'), 'contact_messages', ['is_spam'], unique=False)
    op.create_table('education',
    sa.Column('school', sa.String(length=255), nullable=False),
    sa.Column('school_url', sa.String(length=512), nullable=True),
    sa.Column('school_logo_url', sa.String(length=512), nullable=True),
    sa.Column('degree_fr', sa.String(length=255), nullable=False),
    sa.Column('degree_en', sa.String(length=255), nullable=False),
    sa.Column('field_fr', sa.String(length=255), nullable=True),
    sa.Column('field_en', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_year', sa.Integer(), nullable=True),
    sa.Column('end_year', sa.Integer(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_education'))
    )
    op.create_index(op.f('ix_education_is_visible'), 'education', ['is_visible'], unique=False)
    op.create_index(op.f('ix_education_position'), 'education', ['position'], unique=False)
    op.create_table('experiences',
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('company_url', sa.String(length=512), nullable=True),
    sa.Column('company_logo_url', sa.String(length=512), nullable=True),
    sa.Column('role_fr', sa.String(length=255), nullable=False),
    sa.Column('role_en', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('summary_fr', sa.Text(), nullable=True),
    sa.Column('summary_en', sa.Text(), nullable=True),
    sa.Column('highlights', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tech', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiences'))
    )
    op.create_index(op.f('ix_experiences_is_visible'), 'experiences', ['is_visible'], unique=False)
    op.create_index(op.f('ix_experiences_position'), 'experiences', ['position'], unique=False)
    op.create_index(op.f('ix_experiences_start_date'), 'experiences', ['start_date'], unique=False)
    op.create_table('languages',
    sa.Column('name_fr', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('level_fr', sa.String(length=64), nullable=False),
    sa.Column('level_en', sa.String(length=64), nullable=False),
    sa.Column('cefr', sa.String(length=8), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_languages'))
    )
    op.create_index(op.f('ix_languages_is_visible'), 'languages', ['is_visible'], unique=False)
    op.create_index(op.f('ix_languages_position'), 'languages', ['position'], unique=False)
    op.create_table('nav_items',
    sa.Column('label_fr', sa.String(length=128), nullable=False),
    sa.Column('label_en', sa.String(length=128), nullable=False),
    sa.Column('href', sa.String(length=512), nullable=False),
    sa.Column('location', sa.String(length=16), nullable=False),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_nav_items'))
    )
    op.create_index(op.f('ix_nav_items_is_visible'), 'nav_items', ['is_visible'], unique=False)
    op.create_index(op.f('ix_nav_items_location'), 'nav_items', ['location'], unique=False)
    op.create_index(op.f('ix_nav_items_position'), 'nav_items', ['position'], unique=False)
    op.create_table('organizations',
    sa.Column('slug', sa.String(length=96), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role_fr', sa.String(length=255), nullable=True),
    sa.Column('role_en', sa.String(length=255), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('since', sa.Date(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_index(op.f('ix_organizations_is_visible'), 'organizations', ['is_visible'], unique=False)
    op.create_index(op.f('ix_organizations_position'), 'organizations', ['position'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('page_views',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('path', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=32), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=True),
    sa.Column('referrer', sa.String(length=1024), nullable=True),
    sa.Column('country', sa.String(length=8), nullable=True),
    sa.Column('visitor_hash', sa.String(length=64), nullable=True),
    sa.Column('meta', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_page_views'))
    )
    op.create_index(op.f('ix_page_views_created_at'), 'page_views', ['created_at'], unique=False)
    op.create_index(op.f('ix_page_views_entity_id'), 'page_views', ['entity_id'], unique=False)
    op.create_index(op.f('ix_page_views_entity_type'), 'page_views', ['entity_type'], unique=False)
    op.create_index(op.f('ix_page_views_path'), 'page_views', ['path'], unique=False)
    op.create_index(op.f('ix_page_views_visitor_hash'), 'page_views', ['visitor_hash'], unique=False)
    op.create_table('playlists',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=32), nullable=True),
    sa.Column('topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_playlists'))
    )
    op.create_index(op.f('ix_playlists_external_id'), 'playlists', ['external_id'], unique=False)
    op.create_index(op.f('ix_playlists_is_visible'), 'playlists', ['is_visible'], unique=False)
    op.create_index(op.f('ix_playlists_position'), 'playlists', ['position'], unique=False)
    op.create_index(op.f('ix_playlists_slug'), 'playlists', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('summary_fr', sa.String(length=512), nullable=True),
    sa.Column('summary_en', sa.String(length=512), nullable=True),
    sa.Column('content_fr', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.Column('gallery', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('repo_url', sa.String(length=1024), nullable=True),
    sa.Column('demo_url', sa.String(length=1024), nullable=True),
    sa.Column('article_url', sa.String(length=1024), nullable=True),
    sa.Column('links', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tech', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('role_fr', sa.String(length=255), nullable=True),
    sa.Column('role_en', sa.String(length=255), nullable=True),
    sa.Column('client', sa.String(length=255), nullable=True),
    sa.Column('metrics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('seo_title_fr', sa.String(length=255), nullable=True),
    sa.Column('seo_title_en', sa.String(length=255), nullable=True),
    sa.Column('seo_description_fr', sa.String(length=512), nullable=True),
    sa.Column('seo_description_en', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_category'), 'projects', ['category'], unique=False)
    op.create_index(op.f('ix_projects_is_featured'), 'projects', ['is_featured'], unique=False)
    op.create_index(op.f('ix_projects_is_visible'), 'projects', ['is_visible'], unique=False)
    op.create_index(op.f('ix_projects_position'), 'projects', ['position'], unique=False)
    op.create_index(op.f('ix_projects_published_at'), 'projects', ['published_at'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('sections',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=True),
    sa.Column('title_en', sa.String(length=255), nullable=True),
    sa.Column('subtitle_fr', sa.String(length=512), nullable=True),
    sa.Column('subtitle_en', sa.String(length=512), nullable=True),
    sa.Column('content_fr', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('background', sa.String(length=32), nullable=True),
    sa.Column('max_items', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections'))
    )
    op.create_index(op.f('ix_sections_is_visible'), 'sections', ['is_visible'], unique=False)
    op.create_index(op.f('ix_sections_key'), 'sections', ['key'], unique=True)
    op.create_index(op.f('ix_sections_position'), 'sections', ['position'], unique=False)
    op.create_table('site_settings',
    sa.Column('is_singleton', sa.Boolean(), nullable=False),
    sa.Column('site_name', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('job_title_fr', sa.String(length=255), nullable=False),
    sa.Column('job_title_en', sa.String(length=255), nullable=False),
    sa.Column('tagline_fr', sa.String(length=512), nullable=True),
    sa.Column('tagline_en', sa.String(length=512), nullable=True),
    sa.Column('bio_fr', sa.Text(), nullable=True),
    sa.Column('bio_en', sa.Text(), nullable=True),
    sa.Column('quote_fr', sa.String(length=512), nullable=True),
    sa.Column('quote_en', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('availability_fr', sa.String(length=255), nullable=True),
    sa.Column('availability_en', sa.String(length=255), nullable=True),
    sa.Column('is_open_to_work', sa.Boolean(), nullable=False),
    sa.Column('calendar_url', sa.String(length=512), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('favicon_url', sa.String(length=512), nullable=True),
    sa.Column('og_image_url', sa.String(length=512), nullable=True),
    sa.Column('resume_url_fr', sa.String(length=512), nullable=True),
    sa.Column('resume_url_en', sa.String(length=512), nullable=True),
    sa.Column('seo_title_fr', sa.String(length=255), nullable=True),
    sa.Column('seo_title_en', sa.String(length=255), nullable=True),
    sa.Column('seo_description_fr', sa.String(length=512), nullable=True),
    sa.Column('seo_description_en', sa.String(length=512), nullable=True),
    sa.Column('seo_keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('theme', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('default_locale', sa.String(length=5), nullable=False),
    sa.Column('available_locales', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('analytics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('footer_note_fr', sa.String(length=512), nullable=True),
    sa.Column('footer_note_en', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_site_settings')),
    sa.UniqueConstraint('is_singleton', name=op.f('uq_site_settings_is_singleton'))
    )
    op.create_table('skill_categories',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_fr', sa.String(length=128), nullable=False),
    sa.Column('name_en', sa.String(length=128), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('description_fr', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skill_categories'))
    )
    op.create_index(op.f('ix_skill_categories_is_visible'), 'skill_categories', ['is_visible'], unique=False)
    op.create_index(op.f('ix_skill_categories_position'), 'skill_categories', ['position'], unique=False)
    op.create_index(op.f('ix_skill_categories_slug'), 'skill_categories', ['slug'], unique=True)
    op.create_table('social_links',
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('show_in_header', sa.Boolean(), nullable=False),
    sa.Column('show_in_footer', sa.Boolean(), nullable=False),
    sa.Column('show_in_hero', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links'))
    )
    op.create_index(op.f('ix_social_links_is_visible'), 'social_links', ['is_visible'], unique=False)
    op.create_index(op.f('ix_social_links_position'), 'social_links', ['position'], unique=False)
    op.create_table('stats',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label_fr', sa.String(length=128), nullable=False),
    sa.Column('label_en', sa.String(length=128), nullable=False),
    sa.Column('value', sa.String(length=32), nullable=False),
    sa.Column('suffix', sa.String(length=16), nullable=True),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stats')),
    sa.UniqueConstraint('key', name=op.f('uq_stats_key'))
    )
    op.create_index(op.f('ix_stats_is_visible'), 'stats', ['is_visible'], unique=False)
    op.create_index(op.f('ix_stats_position'), 'stats', ['position'], unique=False)
    op.create_table('tags',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name_fr', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('description_fr', sa.String(length=512), nullable=True),
    sa.Column('description_en', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags'))
    )
    op.create_index(op.f('ix_tags_is_visible'), 'tags', ['is_visible'], unique=False)
    op.create_index(op.f('ix_tags_position'), 'tags', ['position'], unique=False)
    op.create_index(op.f('ix_tags_slug'), 'tags', ['slug'], unique=True)
    op.create_table('testimonials',
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('author_role_fr', sa.String(length=255), nullable=True),
    sa.Column('author_role_en', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('quote_fr', sa.Text(), nullable=True),
    sa.Column('quote_en', sa.Text(), nullable=True),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_testimonials'))
    )
    op.create_index(op.f('ix_testimonials_is_visible'), 'testimonials', ['is_visible'], unique=False)
    op.create_index(op.f('ix_testimonials_position'), 'testimonials', ['position'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locale', sa.String(length=5), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('audit_logs',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('entity_label', sa.String(length=255), nullable=True),
    sa.Column('changes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_logs_actor_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('invitations',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('invited_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], name=op.f('fk_invitations_invited_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitations'))
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('media_assets',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=128), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('folder', sa.String(length=32), nullable=False),
    sa.Column('alt_fr', sa.String(length=255), nullable=True),
    sa.Column('alt_en', sa.String(length=255), nullable=True),
    sa.Column('caption_fr', sa.String(length=512), nullable=True),
    sa.Column('caption_en', sa.String(length=512), nullable=True),
    sa.Column('checksum', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_media_assets_uploaded_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_media_assets_storage_key'))
    )
    op.create_index(op.f('ix_media_assets_checksum'), 'media_assets', ['checksum'], unique=False)
    op.create_index(op.f('ix_media_assets_folder'), 'media_assets', ['folder'], unique=False)
    op.create_table('posts',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('excerpt_fr', sa.String(length=512), nullable=True),
    sa.Column('excerpt_en', sa.String(length=512), nullable=True),
    sa.Column('content_fr', sa.Text(), nullable=True),
    sa.Column('content_en', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('cover_alt_fr', sa.String(length=255), nullable=True),
    sa.Column('cover_alt_en', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reading_minutes', sa.Integer(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('canonical_url', sa.String(length=1024), nullable=True),
    sa.Column('external_url', sa.String(length=1024), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('seo_title_fr', sa.String(length=255), nullable=True),
    sa.Column('seo_title_en', sa.String(length=255), nullable=True),
    sa.Column('seo_description_fr', sa.String(length=512), nullable=True),
    sa.Column('seo_description_en', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_posts_author_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_posts'))
    )
    op.create_index(op.f('ix_posts_is_featured'), 'posts', ['is_featured'], unique=False)
    op.create_index(op.f('ix_posts_is_visible'), 'posts', ['is_visible'], unique=False)
    op.create_index(op.f('ix_posts_position'), 'posts', ['position'], unique=False)
    op.create_index(op.f('ix_posts_published_at'), 'posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_posts_slug'), 'posts', ['slug'], unique=True)
    op.create_index(op.f('ix_posts_status'), 'posts', ['status'], unique=False)
    op.create_table('project_tags',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_project_tags_project_id_projects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_project_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'tag_id', name=op.f('pk_project_tags'))
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('skills',
    sa.Column('category_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['skill_categories.id'], name=op.f('fk_skills_category_id_skill_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_skills'))
    )
    op.create_index(op.f('ix_skills_category_id'), 'skills', ['category_id'], unique=False)
    op.create_index(op.f('ix_skills_is_visible'), 'skills', ['is_visible'], unique=False)
    op.create_index(op.f('ix_skills_position'), 'skills', ['position'], unique=False)
    op.create_table('talks',
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title_fr', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=True),
    sa.Column('organization_id', sa.Uuid(), nullable=True),
    sa.Column('description_fr', sa.Text(), nullable=True),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('abstract_fr', sa.String(length=512), nullable=True),
    sa.Column('abstract_en', sa.String(length=512), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('audience_size', sa.Integer(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('cover_url', sa.String(length=512), nullable=True),
    sa.Column('slides_url', sa.String(length=1024), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('repo_url', sa.String(length=1024), nullable=True),
    sa.Column('event_url', sa.String(length=1024), nullable=True),
    sa.Column('gallery', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('topics', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_talks_organization_id_organizations'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_talks'))
    )
    op.create_index(op.f('ix_talks_event_date'), 'talks', ['event_date'], unique=False)
    op.create_index(op.f('ix_talks_is_featured'), 'talks', ['is_featured'], unique=False)
    op.create_index(op.f('ix_talks_is_visible'), 'talks', ['is_visible'], unique=False)
    op.create_index(op.f('ix_talks_organization_id'), 'talks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_talks_position'), 'talks', ['position'], unique=False)
    op.create_index(op.f('ix_talks_slug'), 'talks', ['slug'], unique=True)
    op.create_index(op.f('ix_talks_type'), 'talks', ['type'], unique=False)
    op.create_table('videos',
    sa.Column('playlist_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('external_id', sa.String(length=64), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], name=op.f('fk_videos_playlist_id_playlists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_videos'))
    )
    op.create_index(op.f('ix_videos_external_id'), 'videos', ['external_id'], unique=False)
    op.create_index(op.f('ix_videos_is_visible'), 'videos', ['is_visible'], unique=False)
    op.create_index(op.f('ix_videos_playlist_id'), 'videos', ['playlist_id'], unique=False)
    op.create_index(op.f('ix_videos_position'), 'videos', ['position'], unique=False)
    op.create_table('post_tags',
    sa.Column('post_id', sa.Uuid(), nullable=False),
    sa.Column('tag_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name=op.f('fk_post_tags_post_id_posts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_post_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id', name=op.f('pk_post_tags'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_tags')
    op.drop_index(op.f('ix_videos_position'), table_name='videos')
    op.drop_index(op.f('ix_videos_playlist_id'), table_name='videos')
    op.drop_index(op.f('ix_videos_is_visible'), table_name='videos')
    op.drop_index(op.f('ix_videos_external_id'), table_name='videos')
    op.drop_table('videos')
    op.drop_index(op.f('ix_talks_type'), table_name='talks')
    op.drop_index(op.f('ix_talks_slug'), table_name='talks')
    op.drop_index(op.f('ix_talks_position'), table_name='talks')
    op.drop_index(op.f('ix_talks_organization_id'), table_name='talks')
    op.drop_index(op.f('ix_talks_is_visible'), table_name='talks')
    op.drop_index(op.f('ix_talks_is_featured'), table_name='talks')
    op.drop_index(op.f('ix_talks_event_date'), table_name='talks')
    op.drop_table('talks')
    op.drop_index(op.f('ix_skills_position'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_visible'), table_name='skills')
    op.drop_index(op.f('ix_skills_category_id'), table_name='skills')
    op.drop_table('skills')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('project_tags')
    op.drop_index(op.f('ix_posts_status'), table_name='posts')
    op.drop_index(op.f('ix_posts_slug'), table_name='posts')
    op.drop_index(op.f('ix_posts_published_at'), table_name='posts')
    op.drop_index(op.f('ix_posts_position'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_visible'), table_name='posts')
    op.drop_index(op.f('ix_posts_is_featured'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_media_assets_folder'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_checksum'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_testimonials_position'), table_name='testimonials')
    op.drop_index(op.f('ix_testimonials_is_visible'), table_name='testimonials')
    op.drop_table('testimonials')
    op.drop_index(op.f('ix_tags_slug'), table_name='tags')
    op.drop_index(op.f('ix_tags_position'), table_name='tags')
    op.drop_index(op.f('ix_tags_is_visible'), table_name='tags')
    op.drop_table('tags')
    op.drop_index(op.f('ix_stats_position'), table_name='stats')
    op.drop_index(op.f('ix_stats_is_visible'), table_name='stats')
    op.drop_table('stats')
    op.drop_index(op.f('ix_social_links_position'), table_name='social_links')
    op.drop_index(op.f('ix_social_links_is_visible'), table_name='social_links')
    op.drop_table('social_links')
    op.drop_index(op.f('ix_skill_categories_slug'), table_name='skill_categories')
    op.drop_index(op.f('ix_skill_categories_position'), table_name='skill_categories')
    op.drop_index(op.f('ix_skill_categories_is_visible'), table_name='skill_categories')
    op.drop_table('skill_categories')
    op.drop_table('site_settings')
    op.drop_index(op.f('ix_sections_position'), table_name='sections')
    op.drop_index(op.f('ix_sections_key'), table_name='sections')
    op.drop_index(op.f('ix_sections_is_visible'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_published_at'), table_name='projects')
    op.drop_index(op.f('ix_projects_position'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_visible'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_featured'), table_name='projects')
    op.drop_index(op.f('ix_projects_category'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_playlists_slug'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_position'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_is_visible'), table_name='playlists')
    op.drop_index(op.f('ix_playlists_external_id'), table_name='playlists')
    op.drop_table('playlists')
    op.drop_index(op.f('ix_page_views_visitor_hash'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_path'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_entity_type'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_entity_id'), table_name='page_views')
    op.drop_index(op.f('ix_page_views_created_at'), table_name='page_views')
    op.drop_table('page_views')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_position'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_is_visible'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_nav_items_position'), table_name='nav_items')
    op.drop_index(op.f('ix_nav_items_location'), table_name='nav_items')
    op.drop_index(op.f('ix_nav_items_is_visible'), table_name='nav_items')
    op.drop_table('nav_items')
    op.drop_index(op.f('ix_languages_position'), table_name='languages')
    op.drop_index(op.f('ix_languages_is_visible'), table_name='languages')
    op.drop_table('languages')
    op.drop_index(op.f('ix_experiences_start_date'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_position'), table_name='experiences')
    op.drop_index(op.f('ix_experiences_is_visible'), table_name='experiences')
    op.drop_table('experiences')
    op.drop_index(op.f('ix_education_position'), table_name='education')
    op.drop_index(op.f('ix_education_is_visible'), table_name='education')
    op.drop_table('education')
    op.drop_index(op.f('ix_contact_messages_is_spam'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_is_read'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_is_archived'), table_name='contact_messages')
    op.drop_index(op.f('ix_contact_messages_email'), table_name='contact_messages')
    op.drop_table('contact_messages')
    op.drop_index(op.f('ix_certifications_position'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_issued_at'), table_name='certifications')
    op.drop_index(op.f('ix_certifications_is_visible'), table_name='certifications')
    op.drop_table('certifications')
    # ### end Alembic commands ###
