"""Re-export every schema so routers can `from app import schemas`."""

from app.schemas.auth import (
    AuditLogOut,
    InvitationAccept,
    InvitationCreate,
    InvitationOut,
    LoginRequest,
    PasswordChange,
    PasswordResetConfirm,
    PasswordResetRequest,
    RefreshRequest,
    SessionOut,
    TokenPair,
    UserCreate,
    UserOut,
    UserUpdate,
)
from app.schemas.common import (
    BulkResult,
    Message,
    OrderedOut,
    ORMModel,
    Page,
    PaginationParams,
    ReorderItem,
    ReorderPayload,
    TimestampedOut,
)
from app.schemas.community import (
    OrganizationCreate,
    OrganizationOut,
    OrganizationUpdate,
    PlaylistCreate,
    PlaylistOut,
    PlaylistUpdate,
    TalkCreate,
    TalkOut,
    TalkUpdate,
    VideoCreate,
    VideoOut,
    VideoUpdate,
)
from app.schemas.content import (
    PostCreate,
    PostOut,
    PostSummaryOut,
    PostUpdate,
    ProjectCreate,
    ProjectOut,
    ProjectSummaryOut,
    ProjectUpdate,
    TagCreate,
    TagOut,
    TagUpdate,
    TagWithCount,
)
from app.schemas.media import (
    ContactMessageCreate,
    ContactMessageOut,
    ContactMessageUpdate,
    DashboardStats,
    MediaAssetOut,
    MediaAssetUpdate,
    PageViewCreate,
    SiteBundle,
    TimeseriesPoint,
    TopEntry,
)
from app.schemas.resume import (
    CertificationCreate,
    CertificationOut,
    CertificationUpdate,
    EducationCreate,
    EducationOut,
    EducationUpdate,
    ExperienceCreate,
    ExperienceOut,
    ExperienceUpdate,
    LanguageCreate,
    LanguageOut,
    LanguageUpdate,
    SkillCategoryCreate,
    SkillCategoryOut,
    SkillCategoryUpdate,
    SkillCreate,
    SkillOut,
    SkillUpdate,
)
from app.schemas.site import (
    HealthOut,
    NavItemCreate,
    NavItemOut,
    NavItemUpdate,
    SectionCreate,
    SectionOut,
    SectionUpdate,
    SiteSettingsOut,
    SiteSettingsUpdate,
    SocialLinkCreate,
    SocialLinkOut,
    SocialLinkUpdate,
    StatCreate,
    StatOut,
    StatUpdate,
    TestimonialCreate,
    TestimonialOut,
    TestimonialUpdate,
)

__all__ = [name for name in dir() if not name.startswith("_")]
